import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import { calculateTaxware } from "./taxwareProxy.js";

dotenv.config({ path: './src/server/.env' });

const { stripe, supabase } = await import("./stripe/stripeClient.js");

const app = express();

app.use(cors());
app.use(express.json());

app.get("/health", (_req, res) => {
  res.send("OK");
});

app.post("/api/taxware/calculate", async (req, res) => {
  try {
    const data = await calculateTaxware(req.body);
    res.json(data);
  } catch (error) {
    res.status(error.status || 500).json({
      error: error.message || "Erreur serveur",
      ...(error.details ? { details: error.details } : {}),
    });
  }
});

app.post("/api/stripe/create-checkout-session", async (req, res) => {
  try {
    const { plan_id, success_url, cancel_url, profile_id, organization_id } = req.body;

    if (!plan_id || !success_url || !cancel_url) {
      return res.status(400).json({ error: 'plan_id, success_url and cancel_url are required' });
    }

    const { data: plan, error: planError } = await supabase
      .from('plans')
      .select('stripe_price_id')
      .eq('id', plan_id)
      .single();

    if (planError || !plan || !plan.stripe_price_id) {
      console.error('Plan not found or stripe_price_id missing', { plan_id, planError, plan });
      return res.status(404).json({ error: 'Plan introuvable ou non configuré avec stripe_price_id' });
    }

    const session = await stripe.checkout.sessions.create({
      mode: 'subscription',
      line_items: [{ price: plan.stripe_price_id, quantity: 1 }],
      success_url,
      cancel_url,
      metadata: {
        plan_id,
        profile_id: profile_id ?? '',
        organization_id: organization_id ?? '',
      },
    });

    return res.json({ url: session.url, id: session.id });
  } catch (error) {
    console.error('create-checkout-session error', error);
    return res.status(500).json({ error: error.message || 'Erreur création session Stripe' });
  }
});

app.post('/api/stripe/webhook', express.raw({ type: 'application/json' }), async (req, res) => {
  const payload = req.body;
  const sig = req.headers['stripe-signature'];

  if (!process.env.STRIPE_WEBHOOK_SECRET) {
    console.error('STRIPE_WEBHOOK_SECRET non défini');
    return res.status(500).send('Webhook non configuré');
  }

  if (!sig) {
    return res.status(400).send('Missing stripe signature');
  }

  let event;
  try {
    event = stripe.webhooks.constructEvent(payload, sig, process.env.STRIPE_WEBHOOK_SECRET);
  } catch (err) {
    console.error('Webhook signature verification failed', err.message);
    return res.status(400).send(`Webhook Error: ${err.message}`);
  }

  try {
    if (event.type === 'checkout.session.completed') {
      const session = event.data.object;
      if (session.subscription) {
        const subscription = await stripe.subscriptions.retrieve(session.subscription);

        const organization_id = session.metadata?.organization_id;
        const plan_id = session.metadata?.plan_id;

        if (!organization_id || !plan_id) {
          console.warn('checkout.session.completed missing metadata', {
            organization_id,
            plan_id,
          });
        } else {
          const billing_cycle = subscription.items?.data?.[0]?.price?.recurring?.interval || null;

          await supabase.from('subscriptions').upsert(
            {
              org_id: organization_id,
              plan_id,
              status: subscription.status,
              stripe_customer_id: subscription.customer,
              stripe_subscription_id: subscription.id,
              current_period_start: subscription.current_period_start
                ? new Date(subscription.current_period_start * 1000).toISOString()
                : null,
              current_period_end: subscription.current_period_end
                ? new Date(subscription.current_period_end * 1000).toISOString()
                : null,
              billing_cycle,
              cancel_at_period_end: subscription.cancel_at_period_end || false,
              // created_at is assumed auto-generated by DB
            },
            { onConflict: 'stripe_subscription_id' }
          );
        }
      }
    }

    if (event.type === 'customer.subscription.updated' || event.type === 'customer.subscription.deleted') {
      const subscription = event.data.object;

      const billing_cycle = subscription.items?.data?.[0]?.price?.recurring?.interval || null;

      const updates = {
        status: subscription.status,
        stripe_customer_id: subscription.customer,
        current_period_start: subscription.current_period_start
          ? new Date(subscription.current_period_start * 1000).toISOString()
          : null,
        current_period_end: subscription.current_period_end
          ? new Date(subscription.current_period_end * 1000).toISOString()
          : null,
        billing_cycle,
        cancel_at_period_end: subscription.cancel_at_period_end || false,
      };

      await supabase
        .from('subscriptions')
        .update(updates)
        .eq('stripe_subscription_id', subscription.id);
    }

    return res.status(200).json({ received: true });
  } catch (err) {
    console.error('Stripe webhook handling error', err);
    return res.status(500).json({ error: err.message || 'Webhook handling error' });
  }
});

const PORT = 3000;

app.listen(PORT, () => {
  console.log(`Server listening on http://localhost:${PORT}`);
});
