import type { DossierClient } from "./types";

export const emptyDossier: DossierClient = {
  identite: {
    prenom: "",
    nom: "",
    age: 0,
    etatCivil: "",
    npa: "",
    commune: "",
    canton: "",
    communeFiscale: "",
    cantonFiscal: "",
    taxwareZip: "",
    taxwareCity: "",
  },
  famille: {
    aConjoint: false,
    ageConjoint: null,
    nombreEnfants: 0,
  },
  revenus: {
    salaire: 0,
    avs: 0,
    lpp: 0,
    autresRevenus: 0,
    totalRevenus: 0,
  },
  immobilier: {
    regimeFiscal: "actuel",
    proprietaireOccupant: false,
    valeurLocativeHabitationPropre: 0,
    interetsHypothecairesHabitationPropre: 0,
    fraisEntretienHabitationPropre: 0,
    possedeBienRendement: false,
    loyersBiensRendement: 0,
    interetsHypothecairesBiensRendement: 0,
    fraisEntretienBiensRendement: 0,
  },
  fortune: {
    liquidites: 0,
    titres: 0,
    troisiemePilier: 0,
    fortuneLppActuelle: 0,
    immobilier: 0,
    fortuneTotale: 0,
  },
  dettes: {
    hypotheques: 0,
    autresDettes: 0,
    totalDettes: 0,
  },
  charges: {
    logement: 0,
    logementIsHypothequeDeductible: false,
    primesMaladie: 0,
    impotsRevenuFortune: 0,
    fraisVie: 0,
    autresCharges: 0,
    autresChargesIsPensionDeductible: false,
    totalCharges: 0,
  },
  fiscalite: {
    revenuImposableIfd: 0,
    revenuImposable: 0,
    fortuneImposableActuelleSaisie: 0,
    troisiemePilierSimule: 0,
    rachatLpp: 0,
    ajustementManuelRevenu: 0,
    correctionFiscaleManuelleIfd: 0,
    correctionFiscaleManuelleCanton: 0,
    correctionFiscaleManuelleFortune: 0,
    impotsEstimes: 0,
    objectifFiscalPrincipal: "",
  },
  objectifs: {
    reduireImpots: false,
    preparerRetraite: false,
    protegerConjoint: false,
    structurerPatrimoine: false,
    transmettre: false,
    anticiperEMS: false,
    objectifPrincipal: "",
  },
};

export const mockDossier: DossierClient = {
  identite: {
  prenom: "Jean",
  nom: "Dupont",
  age: 63,
  etatCivil: "Marié",
  npa: "2000",

  commune: "Neuchâtel",
  canton: "NE",

  communeFiscale: "Neuchâtel",
  cantonFiscal: "NE",

  taxwareZip: "2000",
  taxwareCity: "Neuchâtel",
},
  famille: {
    aConjoint: true,
    ageConjoint: 61,
    nombreEnfants: 0,
  },
  revenus: {
    salaire: 0,
    avs: 36000,
    lpp: 28000,
    autresRevenus: 12000,
    totalRevenus: 76000,
  },
  immobilier: {
    regimeFiscal: "actuel",
    proprietaireOccupant: true,
    valeurLocativeHabitationPropre: 18000,
    interetsHypothecairesHabitationPropre: 9000,
    fraisEntretienHabitationPropre: 3200,
    possedeBienRendement: true,
    loyersBiensRendement: 24000,
    interetsHypothecairesBiensRendement: 6500,
    fraisEntretienBiensRendement: 2100,
  },
  fortune: {
    liquidites: 120000,
    titres: 350000,
    troisiemePilier: 95000,
    fortuneLppActuelle: 420000,
    immobilier: 900000,
    fortuneTotale: 1465000,
  },
  dettes: {
    hypotheques: 300000,
    autresDettes: 10000,
    totalDettes: 310000,
  },
  charges: {
    logement: 18000,
    logementIsHypothequeDeductible: false,
    primesMaladie: 9600,
    impotsRevenuFortune: 18000,
    fraisVie: 42000,
    autresCharges: 8000,
    autresChargesIsPensionDeductible: false,
    totalCharges: 95600,
  },
  fiscalite: {
    revenuImposableIfd: 70000,
    revenuImposable: 70000,
    fortuneImposableActuelleSaisie: 1060000,
    troisiemePilierSimule: 0,
    rachatLpp: 0,
    ajustementManuelRevenu: 0,
    correctionFiscaleManuelleIfd: 0,
    correctionFiscaleManuelleCanton: 0,
    correctionFiscaleManuelleFortune: 0,
    impotsEstimes: 16946,
    objectifFiscalPrincipal: "Réduire les impôts",
  },
  objectifs: {
    reduireImpots: true,
    preparerRetraite: true,
    protegerConjoint: true,
    structurerPatrimoine: true,
    transmettre: false,
    anticiperEMS: false,
    objectifPrincipal: "Réduire les impôts",
  },
};
