import type { AdvisoryContext } from "./recommendationEngine";

export type RecommendationDemoScenario = {
  id: string;
  title: string;
  summary: string;
  tags: string[];
  context: AdvisoryContext;
};

export const recommendationDemoScenarios: RecommendationDemoScenario[] = [
  {
    id: "single-no-children",
    title: "Célibataire sans enfant",
    summary: "Cas simple sans logique familiale ni immobilier.",
    tags: ["Single", "Sans enfant", "Base"],
    context: {
      age: 42,
      partnership: "Single",
      childrenCount: 0,
      totalIncome: 98000,
      totalWealth: 240000,
      hasRealEstate: false,
      realEstateRegime: null,
      taxGainVsBase: 2200,
      variantSpread: 2800,
      recommendedVariantLabel: "Base",
      recommendedVariantRegime: "actuel",
      objectivePrincipal: "Optimisation globale",
      annualMargin: 18000,
      totalTax: 14800,
      hasRetirementObjective: false,
      hasConjointProtectionObjective: false,
      hasTransmissionObjective: false,
      hasStructuringObjective: false,
      hasTaxOptimizationObjective: true,
    },
  },
  {
    id: "couple-no-children",
    title: "Couple sans enfant",
    summary: "Logique couple avec équilibre fiscal et patrimonial.",
    tags: ["Marriage", "Couple", "Sans enfant"],
    context: {
      age: 48,
      partnership: "Marriage",
      childrenCount: 0,
      totalIncome: 132000,
      totalWealth: 520000,
      hasRealEstate: false,
      realEstateRegime: "actuel",
      taxGainVsBase: 2600,
      variantSpread: 3400,
      recommendedVariantLabel: "Variante couple",
      recommendedVariantRegime: "actuel",
      objectivePrincipal: "Réduire la charge fiscale",
      annualMargin: 26000,
      totalTax: 19200,
      hasRetirementObjective: false,
      hasConjointProtectionObjective: true,
      hasTransmissionObjective: false,
      hasStructuringObjective: false,
      hasTaxOptimizationObjective: true,
    },
  },
  {
    id: "couple-with-children",
    title: "Couple avec enfants",
    summary: "Logique familiale, prévoyance et transmission.",
    tags: ["Marriage", "Enfants", "Famille"],
    context: {
      age: 45,
      partnership: "Marriage",
      childrenCount: 2,
      totalIncome: 145000,
      totalWealth: 610000,
      hasRealEstate: false,
      realEstateRegime: "actuel",
      taxGainVsBase: 3100,
      variantSpread: 3900,
      recommendedVariantLabel: "Variante famille",
      recommendedVariantRegime: "actuel",
      objectivePrincipal: "Préparer la retraite",
      annualMargin: 21000,
      totalTax: 20500,
      hasRetirementObjective: true,
      hasConjointProtectionObjective: true,
      hasTransmissionObjective: true,
      hasStructuringObjective: false,
      hasTaxOptimizationObjective: true,
    },
  },
  {
    id: "high-income",
    title: "Revenu élevé",
    summary: "Cas axé sur la pression fiscale et le pilotage des flux.",
    tags: ["Revenu élevé", "Fiscalité"],
    context: {
      age: 44,
      partnership: "Single",
      childrenCount: 0,
      totalIncome: 245000,
      totalWealth: 430000,
      hasRealEstate: false,
      realEstateRegime: null,
      taxGainVsBase: 5400,
      variantSpread: 7600,
      recommendedVariantLabel: "Variante revenus",
      recommendedVariantRegime: "actuel",
      objectivePrincipal: "Réduire la charge fiscale",
      annualMargin: 82000,
      totalTax: 41800,
      hasRetirementObjective: false,
      hasConjointProtectionObjective: false,
      hasTransmissionObjective: false,
      hasStructuringObjective: false,
      hasTaxOptimizationObjective: true,
    },
  },
  {
    id: "high-wealth",
    title: "Fortune élevée",
    summary: "Lecture gouvernance patrimoniale et structuration.",
    tags: ["Fortune élevée", "Structuration"],
    context: {
      age: 53,
      partnership: "Single",
      childrenCount: 0,
      totalIncome: 138000,
      totalWealth: 3250000,
      hasRealEstate: false,
      realEstateRegime: null,
      taxGainVsBase: 2900,
      variantSpread: 5200,
      recommendedVariantLabel: "Variante patrimoine",
      recommendedVariantRegime: "actuel",
      objectivePrincipal: "Structurer et sécuriser le patrimoine",
      annualMargin: 47000,
      totalTax: 26800,
      hasRetirementObjective: false,
      hasConjointProtectionObjective: false,
      hasTransmissionObjective: true,
      hasStructuringObjective: true,
      hasTaxOptimizationObjective: false,
    },
  },
  {
    id: "real-estate",
    title: "Présence immobilière",
    summary: "Cas orienté réforme de la valeur locative et arbitrage immobilier.",
    tags: ["Immobilier", "Réforme", "Valeur locative"],
    context: {
      age: 51,
      partnership: "Marriage",
      childrenCount: 1,
      totalIncome: 168000,
      totalWealth: 890000,
      hasRealEstate: true,
      realEstateRegime: "reforme",
      taxGainVsBase: 3600,
      variantSpread: 6100,
      recommendedVariantLabel: "Variante immobilier",
      recommendedVariantRegime: "reforme",
      objectivePrincipal: "Optimisation globale",
      annualMargin: 29000,
      totalTax: 23600,
      hasRetirementObjective: false,
      hasConjointProtectionObjective: true,
      hasTransmissionObjective: true,
      hasStructuringObjective: false,
      hasTaxOptimizationObjective: true,
    },
  },
  {
    id: "large-gap",
    title: "Écart important entre variantes",
    summary: "Cas où la recommandation doit être plus affirmée.",
    tags: ["Écart fort", "Conclusion affirmée"],
    context: {
      age: 47,
      partnership: "Single",
      childrenCount: 0,
      totalIncome: 158000,
      totalWealth: 720000,
      hasRealEstate: false,
      realEstateRegime: null,
      taxGainVsBase: 8400,
      variantSpread: 9800,
      recommendedVariantLabel: "Variante gagnante",
      recommendedVariantRegime: "actuel",
      objectivePrincipal: "Réduire la charge fiscale",
      annualMargin: 34000,
      totalTax: 22400,
      hasRetirementObjective: false,
      hasConjointProtectionObjective: false,
      hasTransmissionObjective: false,
      hasStructuringObjective: false,
      hasTaxOptimizationObjective: true,
    },
  },
  {
    id: "small-gap",
    title: "Écart faible entre variantes",
    summary: "Cas où la recommandation doit rester nuancée.",
    tags: ["Écart faible", "Conclusion prudente"],
    context: {
      age: 43,
      partnership: "Marriage",
      childrenCount: 0,
      totalIncome: 124000,
      totalWealth: 480000,
      hasRealEstate: false,
      realEstateRegime: "actuel",
      taxGainVsBase: 900,
      variantSpread: 1200,
      recommendedVariantLabel: "Variante équilibrée",
      recommendedVariantRegime: "actuel",
      objectivePrincipal: "Optimisation globale",
      annualMargin: 24000,
      totalTax: 17400,
      hasRetirementObjective: false,
      hasConjointProtectionObjective: true,
      hasTransmissionObjective: false,
      hasStructuringObjective: false,
      hasTaxOptimizationObjective: false,
    },
  },
  {
    id: "senior-long-term",
    title: "Âge élevé / long terme",
    summary: "Cas orienté retraite, progressivité et stabilité dans le temps.",
    tags: ["Senior", "Retraite", "Long terme"],
    context: {
      age: 67,
      partnership: "Marriage",
      childrenCount: 0,
      totalIncome: 118000,
      totalWealth: 1360000,
      hasRealEstate: true,
      realEstateRegime: "actuel",
      taxGainVsBase: 2100,
      variantSpread: 3000,
      recommendedVariantLabel: "Variante retraite",
      recommendedVariantRegime: "actuel",
      objectivePrincipal: "Préparer la retraite",
      annualMargin: 12000,
      totalTax: 19800,
      hasRetirementObjective: true,
      hasConjointProtectionObjective: true,
      hasTransmissionObjective: true,
      hasStructuringObjective: true,
      hasTaxOptimizationObjective: false,
    },
  },
  {
    id: "combined-family-office",
    title: "Cas combiné premium",
    summary: "Couple avec enfants, immobilier, revenu élevé et logique patrimoniale complète.",
    tags: ["Marriage", "Enfants", "Immobilier", "Revenu élevé"],
    context: {
      age: 58,
      partnership: "Marriage",
      childrenCount: 3,
      totalIncome: 315000,
      totalWealth: 2480000,
      hasRealEstate: true,
      realEstateRegime: "reforme",
      taxGainVsBase: 12100,
      variantSpread: 15400,
      recommendedVariantLabel: "Variante family office",
      recommendedVariantRegime: "reforme",
      objectivePrincipal: "Structurer et sécuriser le patrimoine",
      annualMargin: 98000,
      totalTax: 46200,
      hasRetirementObjective: true,
      hasConjointProtectionObjective: true,
      hasTransmissionObjective: true,
      hasStructuringObjective: true,
      hasTaxOptimizationObjective: true,
    },
  },
];
